# Homebrew formula for LeaveSafe. Generated by packaging/generate.sh — edit the
# template in packaging/templates/, not this file.
class Leavesafe < Formula
  desc "Turn your phone into a remote alarm for your laptop"
  homepage "https://github.com/atakankizilyuce/LeaveSafe"
  version "1.3.5"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.5/leavesafe-darwin-arm64"
      sha256 "d2d94b2c066064d7452270970ea46489004d845dea716304b8cf3e3459ad6286"
    end
    on_intel do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.5/leavesafe-darwin-amd64"
      sha256 "87438e30373144cccc2adbcd7cecff6a44dd0cd8fcc186b983b241b52b030c6a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.5/leavesafe-linux-arm64"
      sha256 "1be5cdccc6e74a513269d1a5117e4d0c267a430cdc778501e6fe626f7c89a932"
    end
    on_intel do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.5/leavesafe-linux-amd64"
      sha256 "84950e05fa5883988cb4d24849e07f7032c1972734eb40ea0a60d08210251ef8"
    end
  end

  def install
    # The release assets are bare executables named for their platform; install
    # renames to the command users actually type.
    bin.install Dir["leavesafe-*"].first => "leavesafe"
  end

  def caveats
    <<~EOS
      Run `leavesafe` in a terminal, scan the QR code with your phone, and tap Arm.

      To have it start when you log in:
        leavesafe install-service

      Settings, logs and the event history live in ~/.leavesafe.
    EOS
  end

  test do
    assert_match "LeaveSafe", shell_output("#{bin}/leavesafe -version")
  end
end
