# Homebrew formula for LeaveSafe. Generated by packaging/generate.sh — edit the
# template in packaging/templates/, not this file.
class Leavesafe < Formula
  desc "Turn your phone into a remote alarm for your laptop"
  homepage "https://github.com/atakankizilyuce/LeaveSafe"
  version "1.3.7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.7/leavesafe-darwin-arm64"
      sha256 "e1fe6f437fbd196307f087636467ba04883d3222209980c0a493a8bdb19456ca"
    end
    on_intel do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.7/leavesafe-darwin-amd64"
      sha256 "63ac80ffbd1a073ba880615747b861a156922faef6c26b1f8e05a3f8069013ab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.7/leavesafe-linux-arm64"
      sha256 "d1d21defa986b48157a8694f3fd6e364a970cff86214ca5a8727896cdb062c37"
    end
    on_intel do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.3.7/leavesafe-linux-amd64"
      sha256 "1673d859a498a3f1f12930d4c68ae6674ac0b747d6886b3cc31466eb52cd7220"
    end
  end

  def install
    # The release assets are bare executables named for their platform; install
    # renames to the command users actually type.
    bin.install Dir["leavesafe-*"].first => "leavesafe"
  end

  def caveats
    <<~EOS
      Run `leavesafe` in a terminal, scan the QR code with your phone, and tap Arm.

      To have it start when you log in:
        leavesafe install-service

      Settings, logs and the event history live in ~/.leavesafe.
    EOS
  end

  test do
    assert_match "LeaveSafe", shell_output("#{bin}/leavesafe -version")
  end
end
