# Homebrew formula for LeaveSafe. Generated by packaging/generate.sh — edit the
# template in packaging/templates/, not this file.
class Leavesafe < Formula
  desc "Turn your phone into a remote alarm for your laptop"
  homepage "https://github.com/atakankizilyuce/LeaveSafe"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.6.0/leavesafe-darwin-arm64"
      sha256 "556d229772f428ae407e55c389913274dc776edbe970c702bc4b225b4ea60853"
    end
    on_intel do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.6.0/leavesafe-darwin-amd64"
      sha256 "fc69a597808eba5029c89a94f09351842319a09263d533248f20677d8db2dea6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.6.0/leavesafe-linux-arm64"
      sha256 "35ecb7b985a21a4b34d06179359a5372bf957e64f5cf00c62176b3e66e4b3b69"
    end
    on_intel do
      url "https://github.com/atakankizilyuce/LeaveSafe/releases/download/v1.6.0/leavesafe-linux-amd64"
      sha256 "488b7a26436cc5b9b3c5d5eb899d20cdf24db7413494942e5d0bc8c7d52a2c88"
    end
  end

  def install
    # The release assets are bare executables named for their platform; install
    # renames to the command users actually type.
    bin.install Dir["leavesafe-*"].first => "leavesafe"
  end

  def caveats
    <<~EOS
      Run `leavesafe` in a terminal, scan the QR code with your phone, and tap Arm.

      To have it start when you log in:
        leavesafe install-service

      Settings, logs and the event history live in ~/.leavesafe.
    EOS
  end

  test do
    assert_match "LeaveSafe", shell_output("#{bin}/leavesafe -version")
  end
end
